server:
  port: 9999
spring:
#  redis:
#    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
#    database: 3
#    # redis端口（默认为6379）
#    port: 6379
#    # redis访问密码（默认为空）
#    password: xyj18105857856
#    # redis连接超时时间（单位毫秒）
#    timeout: 0
#    # redis连接池配置
#    pool:
#      # 最大可用连接数（默认为8，负数表示无限）
#      max-active: 8
#      # 最大空闲连接数（默认为8，负数表示无限）
#      max-idle: 8
#      # 最小空闲连接数（默认为0，该值只有为正数才有用）
#      min-idle: 0
#      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#      max-wait: -1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: xyj18105857856 #登陆账号
    password: DWLYJHUAYCMLSXHP #授权码
    port: 25        # 端口
    default-encoding: utf-8
  datasource:
    url: jdbc:mysql://101.43.56.126:3306/keep-health?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: keep-health
    password: keephealth
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml

mybatis:
  # 自动扫描
  type-aliases-package: team.keephealth.yjj.domain.entity
  configuration:
    # 打开延迟加载 的开关
    lazy-loading-enabled: true
    # 将积极加载改为消极加载即按需要加载
    aggressive-lazy-loading: false
    # 开启二级缓存
    cache-enabled: true
    # 支持驼峰命名法
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

cos:
  secretId: AKIDiEUTCeoiMjqgFYaLqADz3wZy71g5E8mB
  secretKey: B5oGRM5FAoCK2WkhNmwqTqwoRnshFXYI
  bucketName: health-1305811591
  region: ap-beijing
  link: https://health-1305811591.cos.ap-beijing.myqcloud.com/
xyj:
  mailFrom: xyj18105857856@163.com
